core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('partner.urls'))
]

partner/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import RedirectView

from .views.auth_views import *
from .views.account_views import *

app_name = 'partner'
urlpatterns = [
    path('', RedirectView.as_view(url='login')),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('registration/success', success_registration, name='success_registration'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='partner:login'), name='logout'),

    path('my/', AccountProfileView.as_view(), name='account_profile'),
    path('my/history/', AccountHistoryView.as_view(), name='account_history'),
    path('my/checkout', CheckoutView.as_view(), name='checkout'),
    path('my/checkout/subscribe', SubscribeView.as_view(), name='subscribe'),
]

partner/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms import TextInput, PasswordInput
from django.utils import timezone
from django.core.exceptions import ValidationError

from .models import User, Partner


class PartnerRegistrationForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Partner
        fields = ('first_name', 'last_name', 'company_name', 'inn', 'phone_number')
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'company_name': 'Наименование компании',
            'inn': 'ИНН',
            'phone_number': 'Номер телефона'
        }
        help_texts = {
            'company_name': 'Укажите, если имеется'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['inn'].widget.attrs.update({'placeholder': '7448963440'})
        self.fields['email'].widget.attrs.update({'placeholder': 'example@example.com'})
        self.fields['phone_number'].widget.attrs.update({'placeholder': '+7 ( 900 ) 123-45-65'})

    def clean_email(self):
        email = self.cleaned_data['email']
        user = None

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            pass

        if user:
            self.add_error('email', 'Аккаунт с таким email уже зарегистрирован.')
            self.fields['email'].widget.attrs['class'] = 'is-invalid'

        return email

    def save(self, commit=True):
        user = User.objects.create_user(self.cleaned_data['email'])
        partner = super().save(commit=False)
        partner.date_registered = timezone.now()
        partner.user = user
        if commit:
            partner.save()
        return partner


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'validate', 'placeholder': 'Email'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'Пароль'}))


class SubscribeForm(forms.Form):
    client_email = forms.EmailField()
    period = forms.IntegerField(widget=forms.Select)
    tariff = forms.ChoiceField(choices=())

    def __init__(self, tariff_json, disable_form=False, *args, **kwargs):
        super(SubscribeForm, self).__init__(*args, **kwargs)
        if disable_form:
            return
        self.fields['tariff'].choices = [(obj['code'], obj['name']) for obj in tariff_json['tariffs']]
        self.tariff_json = tariff_json

        quotas = tariff_json['tariffs'][0]['quotas']
        for quota in quotas:
            code = quota['code']
            self.fields[code] = forms.IntegerField(label=quota['name'])

    def clean(self):
        cleaned_data = super().clean()
        period = cleaned_data['period']
        tariff_code = cleaned_data['tariff']

        tariffs = {}
        for t in self.tariff_json['tariffs']:
            tariffs[t['code']] = t['pricing']

        if str(period) not in tariffs[tariff_code].keys():
            raise ValidationError('input period value не соответствует тарифу')

        return cleaned_data

partner/views/account_views.py
import decimal
import json
from json import loads

import requests as req
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View

from ..forms import SubscribeForm
from ..models import Subscription, Partner


def debug_pricing():
    pricing = \
        '''
    {
    "totalPrice":30990.0,
    "period":12,
    "tariff":{
      "code":"business",
      "name":"Бизнес",
      "price":24990.0
    },
    "options":[],
    "quotas":[],
    "extraOptions":[],
    "extraQuotas":[
      {
        "code":"users",
        "name":"Пользователи",
        "unitPrice":100.0,
        "price":1200.0,
        "quantity":1
      },
      {
        "code":"legal_entities",
        "name":"Юр. лица",
        "unitPrice":200.0,
        "price":4800.0,
        "quantity":2
      }
    ]
    }
    '''
    return loads(pricing)


class Api:
    @staticmethod
    def get(url, *args, **kwargs):
        return Api.__make_request('get', url, *args, **kwargs)

    @staticmethod
    def post(url, data, *args, **kwargs):
        return Api.__make_request('post', url, data, *args, **kwargs)

    @staticmethod
    def __make_request(method, url, data=None, request=None, headers=None, auth=None):
        try:
            if method == "get":
                r = req.get(url, timeout=2, headers=headers, auth=auth, verify=False)
            if method == "post":
                r = req.post(url, data=data, timeout=10, headers=headers, auth=auth, verify=False)
        except (req.Timeout, req.ConnectionError) as e:
            if request:
                messages.warning(request, message="Сервис оформления подписок недоступен.")
            raise ConnectionError
        return Api.__raise_for_status(r, request)

    @staticmethod
    def __raise_for_status(r, request=None):
        try:
            r.raise_for_status()
        except req.HTTPError:
            if request:
                messages.warning(request, message="Сервер оформления подписок недоступен.")
            raise ConnectionError
        return r.json()


# Затычка api
def get_pricing(request):
    """
    Возвращает
     \n tariffs_json = объект тарифов
     \n tariff_obj -- объект тарифа, указанного в request
     \n extra_quotas - extra квоты {code: value}
     \n pricing = {...} -- рассчитанная стоимость подписки
     \n sub_form
    """

    tariffs_json = Api.get('https://adesk.ru/api/tariffs', request=request)

    sub_form = SubscribeForm(tariffs_json, data=request.POST)

    if sub_form.is_valid():

        tariff_code = sub_form.cleaned_data['tariff']
        tariff_obj = next(filter(lambda t: t['code'] == tariff_code, tariffs_json['tariffs']))

        api_data = {
            'client_email': sub_form.cleaned_data['client_email'],
            'period': sub_form.cleaned_data['period'],
            'tariff': tariff_code,
            'extra_quotas': {},
            'extra_options': "[]",
        }

        for quota in tariff_obj['quotas']:
            code = quota['code']
            default_quota_value = quota['quantity']
            extra_value = sub_form.cleaned_data[code] - default_quota_value
            if extra_value > 0:
                api_data['extra_quotas'][code] = extra_value

        api_data['extra_quotas'] = json.dumps(api_data['extra_quotas'])
        headers = {"App-Token": settings.APP_TOKEN_SUBSCRIBE}

        r = Api.post(settings.CHECKOUT_LINK, data=api_data, request=request, auth=settings.DEV_AUTH, headers=headers)

        if r['success'] is False:
            messages.error(request, message=r['message'])
            raise ValidationError(r['message'])

        pricing = r['pricing']
        pricing['quotas_sum'] = sum([q['price'] for q in pricing['extraQuotas']])

        return tariffs_json, tariff_obj, api_data['extra_quotas'], pricing, sub_form

    messages.error(request, message='Данные указаны неверно.')
    raise ValidationError("")


def get_overall(partner):
    revenue_func = F('cost_value') * F('commission') / 100
    return {
        'revenue': Subscription.objects.filter(partner=partner).aggregate(val=Sum(revenue_func)),
        'sales': Subscription.objects.filter(partner=partner).aggregate(Sum('cost_value'))
    }


class AccountProfileView(LoginRequiredMixin, View):
    template_name = 'partner/account/account_page_profile.html'

    def get(self, request):
        try:
            partner = request.user.partner
        except Partner.DoesNotExist:
            return redirect('/admin')

        api_down_messages = [m for m in messages.get_messages(request) if m.level == 30]

        if api_down_messages:
            tariffs_json = None
            subscribe_form = SubscribeForm(None, disable_form=True)
        else:
            try:
                tariffs_json = Api.get('https://adesk.ru/api/tariffs', request=request)
            except ConnectionError:
                return redirect('partner:account_profile')
            subscribe_form = SubscribeForm(tariffs_json)

        overall = get_overall(partner)
        return render(request, self.template_name,
                      context={
                          'partner': partner,
                          'overall': overall,
                          'subscribe_form': subscribe_form,
                          'checkout': False,
                          'tariff_json': tariffs_json,
                          'page': {'profile': {'active': 'active'}}
                      })


class AccountHistoryView(LoginRequiredMixin, View):
    template_name = 'partner/account/account_page_history.html'

    def get(self, request):
        partner = request.user.partner
        subs = reversed(Subscription.objects.filter(partner=partner))
        subs_table = {
            'headers': ('Email', 'Стоимость', 'Заработано', 'Процент комиссии', 'Дата оформления', 'Период', 'Тариф'),
            'dataset': subs
        }

        return render(request, self.template_name,
                      context={
                          'partner': partner,
                          'subs_table': subs_table,
                          'page': {'history': {'active': 'active'}}
                      })


class CheckoutView(LoginRequiredMixin, View):
    template_name = 'partner/account/account_page_profile.html'

    def get(self, request):
        return redirect('partner:account_profile')

    def post(self, request):
        try:
            r = get_pricing(request)
        except (ConnectionError, ValidationError):
            return redirect('partner:account_profile')

        tariffs_json, tariff_obj, extra_quotas, pricing, sub_form = r

        partner = request.user.partner
        overall = get_overall(partner)

        return render(request, self.template_name,
                      context={
                          'partner': partner,
                          'overall': overall,
                          'subscribe_form': sub_form,
                          'checkout': True,
                          'pricing': pricing,
                          'page': {'profile': {'active': 'active'}}
                      })


class SubscribeView(LoginRequiredMixin, View):
    def post(self, request):
        try:
            r = get_pricing(request)
        except (ConnectionError, ValidationError):
            return redirect('partner:account_profile')

        tariffs_json, tariff_obj, extra_quotas, pricing, sub_form = r

        quotas_all = []

        for quota in tariff_obj['quotas']:
            code = quota['code']
            obj = {
                "code": code,
                "name": quota['name'],
                "value": sub_form.cleaned_data[code]
            }
            quotas_all.append(obj)

        partner = request.user.partner

        total_price = decimal.Decimal(pricing['totalPrice'])
        partner_commission = total_price * partner.commission / 100

        api_data = {
            'client_email': sub_form.cleaned_data['client_email'],
            'partner_email': request.user.email,
            'partner_commission': partner_commission,
            'period': sub_form.cleaned_data['period'],
            'tariff': sub_form.cleaned_data['tariff'],
            'extra_quotas': extra_quotas,
            'extra_options': "[]",
        }
        headers = {"App-Token": f"{settings.APP_TOKEN_SUBSCRIBE}"}

        try:
            r = Api.post(settings.SUBSCRIBE_LINK, data=api_data, request=request, headers=headers,
                         auth=settings.DEV_AUTH)
        except ConnectionError:
            return redirect('partner:account_profile')

        if r['success'] is False:
            messages.error(request, message=r['message'])
            return redirect('partner:account_profile')

        tariff_name = pricing['tariff']['name']

        s = Subscription(
            partner=partner,
            email=sub_form.cleaned_data['client_email'],
            cost_value=pricing['totalPrice'],
            commission=partner.commission,
            reg_date=timezone.now(),
            period=sub_form.cleaned_data['period'],
            tariff=tariff_name,
            quotas=quotas_all
        )

        partner.debt += total_price * (1 - partner.commission / 100)
        partner.save(update_fields=['debt'])
        s.save()

        messages.success(request, 'Пользователь успешно подписан.')
        return redirect('partner:account_history')

partner/views/auth_views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.views import View

from ..forms import PartnerRegistrationForm, CustomAuthForm


class RegistrationView(View):
    template_name = 'partner/auth/registration.html'

    def get(self, request):
        form = PartnerRegistrationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = PartnerRegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            request.session['pp_redarekt'] = True
            return redirect('partner:success_registration')

        return render(request, self.template_name, {'form': form})


def success_registration(request):
    if 'pp_redarekt' in request.session:
        del request.session['pp_redarekt']
        return render(request, template_name='partner/auth/success_registration.html')

    return redirect('partner:registration')


class MyLoginView(LoginView):
    template_name = 'partner/auth/login.html'
    next_page = 'partner:account_profile'
    redirect_authenticated_user = True
    authentication_form = CustomAuthForm

partner/templates/partner/account/account_checkout.html
{% load custom_tags %}
{% new_list "client_email" "tariff" "period" as main_list %}

<div class="border p-3 mt-2 mb-3 bg-light rounded m-lg-auto" style="max-width: 500px;" id="form">
    <form action="{% url 'partner:subscribe' %}" method="post" class="row g-2">
        {% csrf_token %}
        {% for field in form %}
            {{ field.as_hidden }}
        {% endfor %}

        <p class="mb-0 fw-bold">Основные параметры</p>
        <hr class="mt-2 mb-0">

        <div class="col-12">
            <label class="form-label">Email пользователя Adesk</label>
            <span class="badge fs-6 bg-secondary fw-normal text-wrap mb-0">{{ form.client_email.value }}</span>
        </div>

        <div class="col-sm-12 mt-3">
            <label class="form-label pe-sm-1">Тариф</label>
            <p class="badge fs-6 bg-secondary fw-normal text-wrap mb-0">{{ form.tariff|choices_display:form.tariff.value}}</p>
            <label class="form-label px-sm-1">на период</label>
            <p class="badge fs-6 bg-secondary fw-normal text-wrap mb-0">{{ form.period.value }}</p><span class="ps-sm-1"> мес.</span>
        </div>

        <div class="col-sm-12 mt-2">
            <label class="form-label pe-sm-1">Стоимость:</label>
            <p class="text-wrap px-2 fs-5 d-inline">{{ pricing.tariff.price }}</p>
        </div>

        <p class="mb-0 fw-bold pt-2">Квоты тарифа</p>
        <hr class="mt-2 mb-0">

        {% for field in form %}
            {% if field.name not in main_list %}
                <div class="col-12">
                    <label class="form-label">{{ field.label }}:</label>
                    <p class="badge ms-3 fs-6 bg-secondary fw-normal text-wrap mb-0">{{ field.value }}</p>
                </div>
            {% endif %}
        {% endfor %}

        {% if pricing.extraQuotas|length > 0 %}
            <div class="col-12 mt-2">
                <label class="form-label pe-sm-1">Стоимость:</label>
                <p class="text-wrap px-2 fs-5 d-inline" style="/* color: #fd7e14; */">
                    {% for extraQuota in pricing.extraQuotas %}
                        {% if not forloop.last %}
                            {{ extraQuota.price }} +
                        {% else %}
                            {{ extraQuota.price }}
                        {% endif %}
                    {% endfor %}
                </p>
                {% if pricing.extraQuotas|length > 1 %}
                    <span class="fs-5"> = {{ pricing.quotas_sum }}</span>
                {% endif %}
            </div>
        {% endif %}

        <div class="col-12 mt-2">
            <div class="mark d-inline py-2">
                <label class="form-label fs-5 pe-sm-1">Итого:</label>
                <p class="text-wrap px-2 fs-5 d-inline">{{ pricing.totalPrice }}</p>
            </div>
        </div>

        <div class="col-12 mt-3 d-sm-flex justify-content-between align-items-end">
                <button type="submit" class="btn btn-primary btn-lg px-4">Оформить подписку</button>
                <a href="{% url 'partner:account_profile' %}" class="text-secondary d-block d-sm-inline pe-sm-2 pb-sm-1 pt-4 pt-sm-0 ps-1 ps-sm-0">Отменить</a>
        </div>

    </form>
</div>

partner/templates/partner/account/account_header.html
<div class="d-flex justify-content-between align-items-center">
    <h3 class="fw-normal">{{ partner.first_name }} {{ partner.last_name }}</h3>
    <h5 class="fw-normal ps-3">{{ partner.user.email }}</h5>
</div>

partner/templates/partner/account/account_navbar.html
<ul class="nav nav-pills my-4 py-1 border-bottom border-2 border-primary" id="pills-tab" role="tablist">


    <li class="nav-item">
        <a href="{% url 'partner:account_profile'%}" class="nav-link {{ page.profile.active }}">Аккаунт</a>
    </li>

    <li class="nav-item">
        <a href="{% url 'partner:account_history'%}" class="nav-link {{ page.history.active }}">История</a>
    </li>

    <li class="nav-item ms-auto">
        <a href="{% url 'partner:logout' %}" class="nav-link">Выход</a>
    </li>


</ul>

partner/templates/partner/account/account_overall.html
<table class="table" style="max-width: 400px;">
    <tbody>
        <tr>
            <td colspan="2" class="fw-bold ps-0">
                Общая информация
            </td>
        </tr>
        <tr>
            <td>ИНН</td>
            <td class="text-end">{{ partner.inn }}</td>
        </tr>
        <tr class="">
            <td style="border-bottom: none">Номер договора</td>
            <td style="border-bottom: none" class="text-end">{{ partner.contract_number }}</td>
        </tr>
        <tr>
            <td colspan="2" class="fw-bold pt-3 ps-0">
                Сводка продаж
            </td>
        </tr>
        <tr>
            <td>Сумма продаж</td>
            <td class="text-end">{{ overall.sales.cost_value__sum|floatformat:"2" }} ₽</td>
        </tr>
        <tr>
            <td>Сумма заработка</td>
            <td class="text-end">{{ overall.revenue.val|floatformat:"2" }} ₽</td>
        </tr>
        <tr>
            <td>Процент комиссии</td>
            <td class="text-end">{{ partner.commission }} %</td>
        </tr>
        <tr>
            <td>Задолженность</td>
            <td class="text-end">{{ partner.debt }} ₽</td>
        </tr>
    </tbody>
</table>

partner/templates/partner/account/account_page_history.html
{% extends 'partner/main.html' %}

{% block title %}
История
{% endblock %}

{% block content %}

    <div class="container mt-4" style="max-width: 1200px;">

        {% include 'partner/account/account_header.html' %}

        {% include 'partner/account/account_navbar.html' %}

        {% if messages %}
            {% for message in messages %}{% endfor %}
            <div class="alert alert-success">Вы успешно подписали пользователя.</div>
        {% endif %}

        {% include 'partner/account/account_subList.html' with subs_table=subs_table %}

    </div>

    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>

{% endblock %}

partner/templates/partner/account/account_page_profile.html
{% extends 'partner/main.html' %}
{% block title %}
Личный кабинет
{% endblock %}

{% block content %}

    <div class="container mt-4" style="max-width: 1200px;">

        {% include 'partner/account/account_header.html' %}

        {% include 'partner/account/account_navbar.html' with page=page %}

        <div class="row">
            <div class="col-lg-4 {% if checkout %}d-lg-block d-none{% endif %}">
                {% include 'partner/account/account_overall.html' with partner=partner overall=overall %}
            </div>
            <div class="col-lg-8">
                {% if not checkout%}{% include 'partner/account/account_subscribe-form.html' with form=subscribe_form tariffs_json=tariff_json %}{% endif %}
                {% if checkout%}{% include 'partner/account/account_checkout.html' with form=subscribe_form pricing=pricing %}{% endif %}
            </div>
        </div>

    </div>

{% endblock %}

partner/templates/partner/account/account_subList.html
{% load tz %}

<div class="mt-4 border table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
            {% for header in subs_table.headers %}
                <th scope="col">
                    {{ header }}
                </th>
            {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in subs_table.dataset %}
                <tr>
                    <td>{{ row.email }}</td>
                    <td>{{ row.cost_value }}</td>
                    <td>{{ row.revenue }}</td>
                    <td>{{ row.commission }}</td>
                    <td>{{ row.reg_date|localtime|date:"d/m/Y G:i" }}</td>
                    <td>{{ row.period }} мес.</td>
                    <td>
                        <button type="button" class="border-0 p-0 bg-transparent text-decoration-underline" data-bs-toggle="tooltip" data-bs-html="true"
                                title="{% for quota in row.quotas %}{{ quota.name }}: {{ quota.value }}<br>{% endfor %}">
                          {{ row.tariff }}
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

partner/templates/partner/account/account_subscribe-form.html
{% load custom_tags %}
{% new_list "client_email" "tariff" "period" as main_list %}

<div class="border p-3 mt-2 mb-3 bg-light rounded m-lg-auto" style="max-width: 500px;">
    <form action="{% url 'partner:checkout' %}#form" method="post" class="row g-2">
        {% csrf_token %}
        <h4 class="fw-normal text-center">Оформить подписку</h4>
        {% if messages %}
            {% for message in messages %}<div class="alert alert-danger mb-0">{{ message }}</div>{% endfor %}
        {% endif %}
        <p class="mb-0 fw-bold">Основные параметры</p>
        <hr class="mt-2 mb-0">


        <div class="col-12">
            <label for="{{ form.email.id_for_label }}" class="form-label">
                Email пользователя Adesk
            </label>
            {{ form.client_email|add_classes:'form-control' }}
        </div>

        <div class="col-sm-8">
            <label for="{{ form.email.id_for_label }}" class="form-label">
                Наименование тарифа
            </label>
            {{ form.tariff|add_classes:'form-control form-select' }}
        </div>
        <div class="col-sm-4">
            <label for="{{ form.email.id_for_label }}" class="form-label">
                Период в месяцах
            </label>
            {{ form.period|add_classes:'form-control form-select' }}
        </div>


        <p class="mb-0 fw-bold pt-2">Квоты тарифа</p>
        <hr class="mt-2 mb-0">


        {% for field in form %}
            {% if field.name not in main_list %}
                <div class="col-sm-6">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field|add_classes:'form-control' }}
                </div>
            {% endif %} 
        {% endfor %}


        <div class="col-12 mt-4 ">
            <button type="submit" class="btn btn-primary px-4" {% if not tariffs_json %}disabled{% endif %}>Продолжить</button>
        </div>
    </form>
</div>

{{ tariffs_json|json_script:"tariffs_json" }}

<script>
    const tariffs = JSON.parse(document.getElementById('tariffs_json').textContent)['tariffs']
    const tariff_select = document.getElementById("id_tariff")
    let period_select = document.getElementById("id_period")

    tariff_select.setAttribute("onchange", "tariff_onchange()")

    function tariff_onchange() {
        let selected_tariff_code = tariff_select.options[tariff_select.selectedIndex].value

        let periods, quotas, isCustomizable;

        for (const tariff of tariffs) {
            if (selected_tariff_code === tariff['code']) {
                periods = tariff['pricing']
                quotas = tariff['quotas']
                isCustomizable = tariff['isCustomizable']
                break;
            }
        }

        period_select.innerHTML = "";

        for (const period of Object.keys(periods)) {
            let opt = document.createElement('option')
            opt.value = period
            opt.innerHTML = period
            period_select.appendChild(opt)
        }

        for (const quota of quotas) {
            let quota_input = document.getElementById(`id_${quota['code']}`)
            quota_input.setAttribute("min", quota['quantity'])
            quota_input.value = quota['quantity']

            if (!isCustomizable)
                quota_input.setAttribute("readonly", "")
            else
                quota_input.removeAttribute("readonly")
        }

    }

    tariff_onchange()
</script>